### ISSUE TITLE
playoff_team column question in 2022 regular season data set

### ISSUE THREAD

**Issue by DPLATA** [fantasydatapros/best-ball-data-bowl#4]
in both the fast and mixed directories of the 2022 bbm regular season data set there are no entries marked with 1 in playoff_team column. I'm wondering why that is, doesn't make sense though because in postseason data sets all of the entries are marked with 1 in that same column.
There's seems to be a mismatch between regular season and postseason.

**Comment by bendominguez0111** [comment]
This is my fault - my description for this column was wrong looking closer now at Hayden Winks' description of the data. playoff_team only tells you whether the round in question is a playoff round, so that's why Regular Season CSVs is all 0s and Playoff CSVs is all 1s. It seems that year over year the meaning of this column changed, which is the source of the confusion here. In 2021, playoff_team did in fact mean => 1: entry advanced, 0: entry did not advance. In 2022, the playoff_team column is only to there to tell you whether the current row is a playoff round. In this case, there might have to be a different process for handling 2021 and 2022 data. I'll check in with some people to confirm this though.

**Comment by bendominguez0111** [comment]
Added this note to the [README.md under `data`](https://github.com/fantasydatapros/best-ball-data-bowl/blob/master/data/README.md):

> Note that the meaning of the playoff_team column changed season over season. In 2022 / BBMII, this column told you whether a team made the playoffs or not. In BBMIII data, however, this column only tells you if the round you're looking at is a playoff round or not. Note that we've already partioned the data for you here based on that column, so if you're working with a regular season CSV, this column will be all 0s (in contrast to BBMII data, this does NOT tell you whether that entry made the playoffs).

**Comment by DPLATA** [comment]
Thanks for the update!
